### ISSUE TITLE
prefer-local does not respect solid:ext option

### ISSUE THREAD

**Issue by miskeens** [devopshq/crosspm#126]
# Details

## Description

When using `prefer-local` to save on transfer with `solid` dependencies, CrossPM unpacks them to cache nevertheless. While it does not appear as an issue on the surface, CrossPM also provides upacked cache content as package root, meaning not only it unpacks the content that does not to be unpacked, but also provides a `PACKAGE_ROOT` output value as path to unpacked content.

This becomes apparent when CI caching is added: as a CI user I'd like to cache `<cpm-cache-path>/archive` directory to be re-used, so I could reproduce similar cpm cache trees without overhead file management.

On a pristine clean launch the issues is not present.

### Commands
```shell
$ crosspm download -o "user=${ci_user},passwd=${ci_passwd},cache=/opt/cpm/cache" --output paths.sh --out-format shell
# on a fresh build <cpm-cache-path>/archive directory is provided as crosspm cache content
$ crosspm download -o "user=${ci_user},passwd=${ci_passwd},cache=/opt/cpm/cache" --output paths.sh --out-format shell
$ source paths.sh
$ cp "$FIXUID_ROOT"/* my/package/dependencies
$ cp "$HUMAOREST_CLIENT_ROOT"/* my/package/dependencies
```

### `crosspm.yaml`
```yaml
cpm:
  description: Configuration for my package
  dependencies: dependencies.txt
  dependencies-lock: dependencies.txt.lock
  cache:
    cmdline: cache
  prefer-local: true

columns: '*package, version, parser'

fails:
  unique:
    - package
    - version

solid:
  ext:
    - '*.vsix'

parsers:
  common:
    sort:
      - version
      - '*'
    index: -1

  fixuid_parser:
    path: '{server}/{repo}/{package}/{package}-{version}-amd64.tar.gz'
    columns:
      version: '{int}.{int}[.{int}]'

  cs_extensions_parser:
    path: '{server}/{repo}/code-server/extensions/{package}-{version}.vsix'
    columns:
      version: '{int}.{int}.{int}[-{str}]'

options:
  user:
    cmdline: user
    env: CROSSPM_USER
    secret: true
  passwd:
    cmdline: passwd
    env: CROSSPM_PASSWORD
    secret: true

common:
  server: https://artifactory-example-server.com/artifactory
  repo: product.third-party
  type: jfrog-artifactory-aql
  auth_type: simple
  auth:
    - '{user}'
    - '{passwd}'

sources:
  - parser: fixuid_parser
  - parser: cs_extensions_parser
```
### `dependencies.txt`/`dependencies.txt.lock`
```
#package            version parser
fixuid              *       fixuid_parser
humao.rest-client   *       cs_extensions_parser
```
```
#package          version parser
fixuid            0.5     fixuid_parser
humao.rest-client 0.25.1  cs_extensions_parser
```

## Expected result
Unpacked binaries are copied as unpacked binaries, packed (solid) binaries are copied "as is".

## Actual result
Both unpacked and packed (solid) binaries are copied as unpacked binaries.
